version: '3'
services:
  sandbox_dev:
    build:
      context: ..
      dockerfile: .docker/Dockerfile.dev
    network_mode: host
    volumes:
      - ..:/workspace:Z
    command: "sleep infinity"
    platform: linux/amd64
    env_file: ../.env
